# Generated by Django 5.1 on 2024-09-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
