# Generated by Django 5.1 on 2024-09-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0002_alter_user_role_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='firstname',
        ),
    ]
