# Generated by Django 5.1 on 2024-10-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
