# Generated by Django 5.1 on 2024-10-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0003_rename_username_user_firstname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
    ]
