# Generated by Django 5.1 on 2024-10-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0003_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='status',
            new_name='account_status',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='status',
            new_name='account_status',
        ),
        migrations.AlterField(
            model_name='admin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
