# Generated by Django 5.1.1 on 2024-09-23 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('customerID', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_mgmt.product')),
            ],
        ),
    ]
