# Generated by Django 5.1 on 2024-10-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order_Management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
