# Generated by Django 5.1.1 on 2024-09-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='paymentInfo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='wishlist',
        ),
    ]
