# Generated by Django 5.1 on 2024-10-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='pincode',
            field=models.CharField(default=None, max_length=6),
        ),
    ]
