# Generated by Django 5.1 on 2024-10-01 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0004_alter_user_firstname'),
        ('user_mgmt', '0004_alter_customerprofile_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_console.user'),
        ),
    ]
