# Generated by Django 5.1 on 2024-10-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productID', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=30)),
                ('Model', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('category', models.CharField(choices=[('ELECTRONICS', 'Electronics'), ('KITCHEN APPLIANCES', 'Kitchen Appliances'), ('HOME APPLIANCES', 'Home Appliances'), ('ENTERTAINMENT', 'Entertainment'), ('BOOKS', 'Books')], max_length=20)),
                ('imageUrl', models.URLField(blank=True)),
            ],
        ),
    ]
