# Generated by Django 5.1.1 on 2024-09-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ELEC', 'Electronics'), ('FASH', 'Fashion'), ('TOYS', 'Toys')], max_length=20),
        ),
    ]
