# Generated by Django 5.1 on 2024-10-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='productname',
        ),
    ]
