# Generated by Django 5.1 on 2024-10-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_mgmt', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='productID',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
