# Generated by Django 4.1.13 on 2024-10-29 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0004_rename_status_admin_account_status_and_more'),
        ('product_mgmt', '0004_review_rated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_console.user', unique=True),
        ),
    ]
