# Generated by Django 5.1 on 2024-10-09 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_console', '0003_user_last_updated'),
        ('product_mgmt', '0005_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_mgmt.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_console.user')),
            ],
        ),
    ]
