# Generated by Django 5.1.1 on 2024-11-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_console', '0001_initial'),
        ('cart_mgmt', '0001_initial'),
        ('product_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_mgmt.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_console.user')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
